### ISSUE TITLE
how to plot figure 4?

### ISSUE THREAD

**Issue by liamxg** [flu-crew/antigenic-prediction#1]
@mazeller

**Comment by mazeller** [comment]
Hello Liam, Figure 4 was rendered in pymol. To achieve this, we needed to create a list of residue selection and coloring commands to feed into pymol based on the importance scores given to use from the random forest algorithm. 

This is achieved in the R script features.R at antigenic-prediction\paper_figures\importance_figure, with lines 50 and onward being important for mapping the color value onto the position. The output, color.csv was used to make colorList.csv in the same folder, which column F is just the excel formula ‘=CONCAT("0x",RIGHT(E2,6))’ and column G is a formula similar to ‘=CONCAT("select resi ",A2, ";color ",F2,", sele;")’. Retrospectively, I could have saved time by doing both of these steps within the R script itself.

The 4O5N.pdb in the folder from RCSB can be loaded into pymol. The entire contents of G can be pasted as is into pymol to color the matching residues. For this figure, I applied a base color of gray90 or gray80 to exclude positions without importance before pasting my coloring commands. After, I hid all of the model and showed the protein as a surface. Please refer to the ray commands for pymol at https://pymolwiki.org/index.php/Ray for rendering.

**Comment by liamxg** [comment]
@mazeller thanks for your kindly reply, look like to complex to me. :)

**Comment by liamxg** [comment]
Retrospectively, I could have saved time by doing both of these steps within the R script itself.  can you write the code for this, thanks.
